// scripts/components/PaydayForm.tsx
import { useState, useMemo } from "react";
import frequencyTypes from "@/frequencyTypes";
import nthFormatter from "@/nth-formatter";
import weekdays from "@/weekdays";
import type { Payday } from "@/types/Payday";

interface Props {
  value: number;
  frequencyId: string;
  onChange: (value: number) => void;
}

function format(frequencyId: string, payday: number): string {
  if (frequencyId === frequencyTypes.weekly) return weekdays.getName(payday);
  return nthFormatter.format(payday);
}

function buildPaydays(frequencyId: string, upperBound: number): Payday[] {
  const result: Payday[] = [];
  for (let i = 1; i <= upperBound; i++) {
    result.push({ id: i, name: format(frequencyId, i) });
  }
  return result;
}

export default function PaydayForm({ value, frequencyId, onChange }: Props) {
  const [isFormVisible, setIsFormVisible] = useState(false);

  const paydayName = format(frequencyId, value);

  const paydays = useMemo(() => {
    const upperBound = frequencyId === frequencyTypes.weekly ? 7 : 31;
    return buildPaydays(frequencyId, upperBound);
  }, [frequencyId]);

  const handleChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    setIsFormVisible(false);
    onChange(parseInt(event.target.value));
  };

  return (
    <div>
      <h3>Payday</h3>
      <div className="payday-info">
        <p style={{ display: isFormVisible ? "" : "none" }}>
          <select value={value} onChange={handleChange}>
            {paydays.map((p) => (
              <option value={p.id} key={p.id}>
                {p.name}
              </option>
            ))}
          </select>
          <a
            href="#"
            onClick={(e) => {
              e.preventDefault();
              setIsFormVisible(false);
            }}
          >
            Cancel
          </a>
        </p>
        <p style={{ display: isFormVisible ? "none" : "" }}>
          {paydayName}{" "}
          <a
            href="#"
            onClick={(e) => {
              e.preventDefault();
              setIsFormVisible(true);
            }}
          >
            Change
          </a>
        </p>
      </div>
    </div>
  );
}

// Web/app/scripts/components/PaydayForm.vue
﻿<template>
    <div>
        <h3>Payday</h3>
        <div class="payday-info">
            <p v-show="isFormVisible">
                <select :value="value" v-on:input="updateValue">
                    <option v-for="p in paydays" :value="p.id" :key="p.id">{{p.name}}</option>
                </select>
                <a href="#" @click.prevent="close">Cancel</a>
            </p>
            <p v-show="!isFormVisible">
                {{paydayName}}
                <a href="#" @click.prevent="open">Change</a>
            </p>
        </div>
    </div>
</template>

<script setup lang="ts">
    import frequencies from '@/frequencies';
    import nthFormatter from '@/nth-formatter';
    import weekdays from '@/weekdays';
    import { Payday } from '@/types/Payday';
    import { computed, ref } from 'vue';

    const props = defineProps<{
        value: number,
        frequencyId: string
    }>();

    const emit = defineEmits(['input']);

    const isFormVisible = ref(false);

    const paydayName = computed(() => {
        return format(props.frequencyId, props.value);
    });

    const paydays = computed(() => {
        return getPayDays(props.frequencyId);
    });

    const getPayDays = (frequencyId: string) => {
        if (frequencyId === frequencies.weekly)
            return getWeeklyPaydays(frequencyId);
        return getMonthlyPaydays(frequencyId);
    }

    const getWeeklyPaydays = (frequencyId: string) => {
        return getPaydaysArray(frequencyId, 7);
    }

    const getMonthlyPaydays = (frequencyId: string) => {
        return getPaydaysArray(frequencyId, 31);
    }

    const getPaydaysArray = (frequencyId: string, upperBound: number): Payday[] => {
        const paydays: Payday[] = [];

        for (let i = 1; i <= upperBound; i++) {
            paydays.push({ id: i, name: format(frequencyId, i) });
        }
        return paydays;
    }

    const format = (frequencyId: string, payday: number) => {
        if (frequencyId === frequencies.weekly)
            return weekdays.getName(payday);
        return nthFormatter.format(payday);
    }

    const open = (): void => {
        isFormVisible.value = true;
    };

    const close = (): void => {
        isFormVisible.value = false;
    };

    const updateValue = (event: Event) => {
        close();
        const value = (event.target as HTMLInputElement).value;
        emit('input', value);
    }
</script>
