// scripts/components/TimezoneForm.tsx
import { useState } from 'react';
import type { Timezone } from '@/types/Timezone';

interface Props {
  value: string;
  timezones: Timezone[];
  onChange: (value: string) => void;
}

export const TimezoneForm = ({ value, timezones, onChange }: Props) => {
  const [isFormVisible, setIsFormVisible] = useState(false);

  const timezoneName = timezones.find((t) => t.id === value)?.name ?? '';

  const handleChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    setIsFormVisible(false);
    onChange(event.target.value);
  };

  if (!timezones.length) return null;

  return (
    <div>
      <h3>Timezone</h3>
      <div className="timezone-info">
        <p style={{ display: isFormVisible ? '' : 'none' }}>
          <select value={value} onChange={handleChange}>
            {timezones.map((t) => (
              <option value={t.id} key={t.id}>
                {t.name}
              </option>
            ))}
          </select>
          <a
            href="#"
            onClick={(e) => {
              e.preventDefault();
              setIsFormVisible(false);
            }}
          >
            Cancel
          </a>
        </p>
        <p style={{ display: isFormVisible ? 'none' : '' }}>
          {timezoneName}{' '}
          <a
            href="#"
            onClick={(e) => {
              e.preventDefault();
              setIsFormVisible(true);
            }}
          >
            Change
          </a>
        </p>
      </div>
    </div>
  );
};

// Web/app/scripts/components/TimezoneForm.vue
﻿<template>
    <div v-if="isReady">
        <h3>Timezone</h3>
        <div class="timezone-info">
            <p v-show="isFormVisible">
                <select :value="value" v-on:input="updateValue">
                    <option v-for="t in timezones" :value="t.id" :key="t.id">{{t.name}}</option>
                </select>
                <a href="#" @click.prevent="close">Cancel</a>
            </p>
            <p v-show="!isFormVisible">
                {{timezoneName}}
                <a href="#" @click.prevent="open">Change</a>
            </p>
        </div>
    </div>
</template>

<script setup lang="ts">
    import { Timezone } from '@/types/Timezone';
    import { computed, ref } from 'vue';

    const props = defineProps<{
        value: string,
        timezones: Timezone[]
    }>();

    const emit = defineEmits(['input']);

    const isFormVisible = ref(false);

    const timezoneName = computed(() => {
        for (const c of props.timezones) {
                if (c.id === props.value) {
                    return c.name;
                }
            }
            return '';
    });

    const isReady = computed(() => {
        return !!props.timezones.length;
    });

    const open = (): void => {
        isFormVisible.value = true;
    };

    const close = (): void => {
        isFormVisible.value = false;
    };

    const updateValue = (event: Event) => {
        close();
        const value = (event.target as HTMLInputElement).value;
        emit('input', value);
    }
</script>
