// scripts/App.tsx
import { useState, useEffect, useMemo } from 'react';
import { useQuery } from '@tanstack/react-query';
import dayjs from 'dayjs';
import advancedFormat from 'dayjs/plugin/advancedFormat';
import CountryForm from '@/components/CountryForm';
import TimezoneForm from '@/components/TimezoneForm';
import FrequencyForm from '@/components/FrequencyForm';
import PaydayForm from '@/components/PaydayForm';
import type { Country } from '@/types/Country';
import type { Frequency } from '@/types/Frequency';
import type { Timezone } from '@/types/Timezone';
import type { PaydayResponse } from '@/types/PaydayResponse';
import ajax from '@/ajax';
import urls from '@/urls';
import defaults from '@/defaults';
import storage from '@/storage';
import frequencyTypes from '@/frequencyTypes';

dayjs.extend(advancedFormat);

const getTimezones = (): Timezone[] => {
  const ids = (Intl as any).supportedValuesOf('timeZone') as string[];
  return ids.map((id: string) => ({ id, name: id }));
};

export default function App() {
  const [payday, setPayday] = useState(() => storage.getPayday());
  const [timezone, setTimezone] = useState(() => storage.getTimezone());
  const [frequency, setFrequency] = useState(() => storage.getFrequency());
  const [country, setCountry] = useState(() => storage.getCountry());

  const email = 'info@isitpayday.com';
  const apiHost = 'api.isitpayday.com';

  const paydayUrl =
    frequency === frequencyTypes.weekly ? urls.weeklyUrl(payday, timezone, country) : urls.monthlyUrl(payday, timezone, country);

  const { data: optionsData, isSuccess: isOptionsReady, isError: isOptionsError } = useQuery({
    queryKey: ['options'],
    queryFn: async () => {
      const [countriesResponse, frequenciesResponse] = await Promise.all([
        ajax.get<Country[]>(urls.countriesUrl),
        ajax.get<Frequency[]>(urls.frequenciesUrl),
      ]);
      return { countries: countriesResponse, frequencies: frequenciesResponse, timezones: getTimezones() };
    },
  });

  const { data: paydayData, isSuccess: isPaydayReady, isError: isPaydayError } = useQuery({
    queryKey: ['payday', paydayUrl],
    queryFn: () => ajax.get<PaydayResponse>(paydayUrl),
  });

  useEffect(() => {
    if (!optionsData) return;
    const isSavedTimezoneValid = !!optionsData.timezones.find((tz) => tz.id === timezone);
    if (!isSavedTimezoneValid) {
      const defaultTz = defaults.getDefaultTimezone();
      storage.saveTimezone(defaultTz);
      setTimezone(defaultTz);
    }
  }, [optionsData]);

  const countries = optionsData?.countries ?? [];
  const frequencies = optionsData?.frequencies ?? [];
  const timezones = optionsData?.timezones ?? [];
  const isPayday = paydayData?.isPayDay ?? false;
  const nextPayday = paydayData ? new Date(paydayData.nextPayDay) : null;
  const localTime = paydayData?.localTime ?? '';

  const error = isOptionsError ? 'Error loading options' : isPaydayError ? 'Error loading payday' : '';
  const isReady = isPaydayReady && isOptionsReady;
  const message = error ? 'Error' : isPayday ? 'YES!!1!' : 'No =(';

  const nextPaydayMessage = useMemo(() => {
    if (nextPayday === null) return '';
    return `Next payday is ${dayjs(nextPayday).format('MMM D')}`;
  }, [nextPayday]);

  const formattedLocalTime = useMemo(() => {
    if (localTime) return dayjs(localTime).format('MMM D YYYY, HH:mm:ss');
    return '';
  }, [localTime]);

  const mailtoUrl = `mailto:${email}`;
  const apiUrl = `https://${apiHost}`;

  const handleCountryChange = (newCountry: string) => {
    storage.saveCountry(newCountry);
    setCountry(newCountry);
  };

  const handleTimezoneChange = (newTimezone: string) => {
    storage.saveTimezone(newTimezone);
    setTimezone(newTimezone);
  };

  const handlePaydayChange = (newPayday: number) => {
    storage.savePayday(newPayday);
    setPayday(newPayday);
  };

  const handleFrequencyChange = (newFrequency: string) => {
    storage.saveFrequency(newFrequency);
    const newPayday = newFrequency === frequencyTypes.weekly ? defaults.weeklyPayday : defaults.monthlyPayday;
    storage.savePayday(newPayday);
    setFrequency(newFrequency);
    setPayday(newPayday);
  };

  if (!isReady) return null;

  return (
    <div>
      <p className="message">
        <span>{message}</span>
      </p>
      {!isPayday && <p className="next-payday">{nextPaydayMessage}</p>}
      {error && (
        <p className="error">
          <span>{error}</span>
        </p>
      )}
      <div className="settings">
        <h2>Settings</h2>
        <FrequencyForm value={frequency} frequencies={frequencies} onChange={handleFrequencyChange} />
        <PaydayForm value={payday} frequencyId={frequency} onChange={handlePaydayChange} />
        <CountryForm value={country} countries={countries} onChange={handleCountryChange} />
        <TimezoneForm value={timezone} timezones={timezones} onChange={handleTimezoneChange} />
      </div>
      <p className="footer">{formattedLocalTime}</p>
      <p className="contact">
        Api: <a href={apiUrl}>{apiHost}</a>
        <br />
        Bugs and suggestions: <a href={mailtoUrl}>{email}</a>
      </p>
    </div>
  );
}

// scripts/App.vue
﻿<template>
  <div v-if="isReady">
    <p class="message">
      <span>{{ message }}</span>
    </p>
    <p class="next-payday" v-if="!isPayday">{{ nextPaydayMessage }}</p>
    <p class="error" v-if="hasError">
      <span>{{ error }}</span>
    </p>
    <div class="settings">
      <h2>Settings</h2>
      <FrequencyForm v-model="frequency" :frequencies="frequencies" />
      <PaydayForm v-model="payday" :frequencyId="frequency" />
      <CountryForm v-model="country" :countries="countries" />
      <TimezoneForm v-model="timezone" :timezones="timezones" />
    </div>
    <p class="footer">{{ formattedLocalTime }}</p>
    <p class="contact">
      Api: <a :href="apiUrl">{{ apiHost }}</a>
      <br />
      Bugs and suggestions: <a :href="mailtoUrl">{{ email }}</a>
    </p>
  </div>
</template>

<script setup lang="ts">
import dayjs from "dayjs";
import CountryForm from "./components/CountryForm.vue";
import TimezoneForm from "./components/TimezoneForm.vue";
import FrequencyForm from "./components/FrequencyForm.vue";
import PaydayForm from "./components/PaydayForm.vue";
import { Country } from "@/types/Country";
import { Frequency } from "@/types/Frequency";
import { Timezone } from "@/types/Timezone";
import { PaydayResponse } from "@/types/PaydayResponse";
import ajax from "./ajax";
import urls from "./urls";
import defaults from "./defaults";
import storage from "./storage";
import frequencyTypes from "./frequencyTypes";
import advancedFormat from "dayjs/plugin/advancedFormat";
import { computed, onMounted, ref, watch } from "vue";

dayjs.extend(advancedFormat);

const error = ref("");
const isOptionsReady = ref(false);
const isPaydayReady = ref(false);
const isPayday = ref(false);
const nextPayday = ref<Date | null>(null);
const localTime = ref("");
const payday = ref(defaults.payday);
const timezone = ref(defaults.getDefaultTimezone());
const frequency = ref(defaults.frequency);
const country = ref(defaults.country);
const countries = ref<Country[]>([]);
const timezones = ref<Timezone[]>([]);
const frequencies = ref<Frequency[]>([]);
const email = ref("info@isitpayday.com");

const isReady = computed(() => {
  return isPaydayReady.value && isOptionsReady.value;
});

const message = computed(() => {
  if (error.value) return "Error";
  return isPayday.value ? "YES!!1!" : "No =(";
});

const nextPaydayMessage = computed(() => {
  if (nextPayday.value === null) return "";

  var formattedDate = dayjs(nextPayday.value).format("MMM D");
  return `Next payday is ${formattedDate}`;
});

const formattedLocalTime = computed(() => {
  if (localTime.value)
    return dayjs(localTime.value).format("MMM D YYYY, HH:mm:ss");
  return "";
});

const hasError = computed(() => {
  return !!error.value;
});

const mailtoUrl = computed(() => {
  return `mailto:${email.value}`;
});

const apiHost = "api.isitpayday.com";

const apiUrl = computed(() => {
  return `https://${apiHost}`;
});

watch(country, (oldVal, newVal) => {
  storage.saveCountry(country.value);
  loadPayday();
});

watch(frequency, (oldVal, newVal) => {
  storage.saveFrequency(frequency.value);
  payday.value =
    frequency.value === frequencyTypes.weekly
      ? defaults.weeklyPayday
      : defaults.monthlyPayday;
  storage.savePayday(payday.value);
  loadPayday();
});

watch(timezone, (oldVal, newVal) => {
  storage.saveTimezone(timezone.value);
  loadPayday();
});

watch(payday, (oldVal, newVal) => {
  storage.savePayday(payday.value);
  loadPayday();
});

watch(isOptionsReady, (oldVal, newVal) => {
  const isSavedTimezoneValid = !!timezones.value.find(
    (tz) => tz.id === timezone.value,
  );

  if (!isSavedTimezoneValid) {
    timezone.value = defaults.getDefaultTimezone();
    storage.saveTimezone(timezone.value);
  }
});

const loadSettings = () => {
  country.value = storage.getCountry();
  frequency.value = storage.getFrequency();
  timezone.value = storage.getTimezone();
  payday.value = storage.getPayday();
};

const loadPayday = async () => {
  try {
    const response = await ajax.get<PaydayResponse>(paydayUrl.value);
    isPayday.value = response.isPayDay;
    nextPayday.value = new Date(response.nextPayDay);
    localTime.value = response.localTime;
    isPaydayReady.value = true;
  } catch (e) {
    error.value = "Error loading payday";
  }
};

const loadOptions = async () => {
  try {
    const [countriesResponse, frequenciesResponse] = await Promise.all([
      ajax.get<Country[]>(urls.countriesUrl),
      ajax.get<Frequency[]>(urls.frequenciesUrl),
    ]);
    countries.value = countriesResponse;
    frequencies.value = frequenciesResponse;
    timezones.value = getTimezones();
    isOptionsReady.value = true;
  } catch (e) {
    error.value = "Error loading options";
  }
};

const getTimezones = () => {
  const ids = (Intl as any).supportedValuesOf("timeZone") as string[];
  return ids.map((id: string) => {
    return {
      id: id,
      name: id,
    };
  });
};

const paydayUrl = computed(() => {
  return frequency.value === frequencyTypes.weekly
    ? urls.weeklyUrl(payday.value, timezone.value, country.value)
    : urls.monthlyUrl(payday.value, timezone.value, country.value);
});

onMounted(async () => {
  loadSettings();
  await Promise.all([loadPayday(), loadOptions()]);
});
</script>
